dist: bionic
language: minimal
services: docker


jobs:
  include:
    - stage: build docker image
      script:
      - docker images
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
