dist: bionic
language: minimal
services: docker

jobs:
    include:
        - stage: build
        script:
        - docker images

# jobs:
#     include:
#     - stage: build docker images
#     script:
    # - docker build -t deltaclock/pwntools:2 py2/
    # - docker build -t deltaclock/pwntools:3 py3/
    # - docker build -t deltaclock/pwntools py3/
    # - docker images
    # - stage: deploy
    # script:
    # - echo "$DOCKER_TOKEN" | docker login -u "deltaclock" --password-stdin
    # - docker push deltaclock/pwntools:2
    # - docker push deltaclock/pwntools:3
    # - docker push deltaclock/pwntools