dist: bionic
language: minimal
services: docker


jobs:
  include:
    - stage: build docker image
      script:
      - docker images
      - echo yes
    - stage: deploy
      script:
      - echo deploy
